let easyar = ["stereo madness",
"back on track",
"polargeist",
"dry out",
"base after base",
"can't let go",
"jumper",
"time machine",
"cycles",
"xstep",
"clutterfunk",
"theory of everything",
"electroman adventures",
"clubstep",
"electrodynamix",
"hexagon force",
"blast processing",
"theory of everything 2",
"geometrical dominator",
"deadlocked",
"fingerdash",
"retray",
"the nightmare",
"outerspace",
"amplification",
"acid factory",
"spooky light",
"retro circles",
"butiti",
"butiti iii",
"chambers",
"mind control",
"lustre",
"victim",
"extinction",
"ghoul",
"unity",
"first race",
"dinosaur",
"frontline full",
"mystery dungeon",
"tetrix",
"portal",
"ground zero",
"fire aura",
"generation retro",
"crimson clutter",
"hypersonic",
"la campanella",
"crescendo",
"flappy bird",
"scarlet surge",
"technoloid",
"subsonic",
"digital descent",
"mr crazyhands",
"geometry dash",
"zodiac",
"high life",
"xo",
"christmas box",
"subscribers power",
"utopian world",
"slaughterhouse",
"abyss of darkness",
"aerial gleam",
"bloodlust",
"cognition",
"crimson planet",
"fusion z",
"kowareta",
"kuzureta",
"wasureta",
"plasma pulse finale",
"renevant",
"sary never clear",
"sonic wave infinity",
"tartarus",
"rust",
"trueffet",
"firework",
"sakupen circles",
"silent clubstep",
"black blizzard",
"manix",
"dont rate this level",
"conical depression",
"the triple trial",
"the real flappy bird",
"kappaclysm",
"magmatic sanctuary",
"payload",
"carnation",
"schade",
"end of line",
"adrift",
"endless",
"sonar",
"electroworld",
"globe navigation",
"lunar ocean",
"edification",
"sunset",
"aquaris"
]
let hardar = ["dark paradise",
"infernal arena",
"vignette",
"panasonic",
"poltergeist",
"dark travel",
"ice carbon diablo x",
"invisible deadlocked",
"slaughterhouse",
"heartbeat",
"ditched machine",
"megalovania",
"ultra drivers",
"the robotic rush",
"syobon action",
"slam",
"buck force",
"castlemania",
"falling up",
"death corridor",
"pp",
"goldenclub",
"arcturus",
"frozen cave",
"keres",
"verdant landscape",
"low death",
"hungry humphrey",
"shock",
"fernafloo 3",
"danger zone",
"beginning of time",
"colorz",
"phantom",
"the world",
"overture",
"anubis",
"warmth"
]
let impossiblear = [ "impulse",
"lights and thunder",
"hextec flow",
"blue hell",
"motion",
"infinite circles",
"chaotic",
"horizon",
"ice of dawn",
"toxin lab ii",
"electro rand",
"crunchy apple",
"inundation",
"honor step",
"dandash",
"culmination",
"dawns room",
"eclipse",
"ash and dust",
"c s q n",
"neon sawblade",
"cadence",
"high spirits",
"havoc",
"psyworm",
"electric flare",
"ohhh my gloww",
"rebirth",
"163",
"envy",
"shaolin warrior",
"fragmented calamity",
"bee",
"twister",
"verde",
"clubbin",
"electronic clubstep",
"ego death",
"dark drop"
]
let dir = "lvls/"
let fmt = ".jpg";
document.title = "Угадайка уровней Geometry Dash";
function getRandomInt(min, max) 
{
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
